name: Release

permissions: {}

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    name: Release
    uses: grafana/xk6/.github/workflows/extension-release.yml@v0.20.1
    permissions:
      contents: write
    with:
      go-version: "1.24.x"
      os: '["linux", "windows", "darwin"]'
      arch: '["amd64", "arm64"]'
      k6-version: "v1.0.0"
      xk6-version: "0.20.1"
